joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

left_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: wheel_left_joint

right_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: wheel_right_joint
